### ISSUE TITLE
Discog images

### ISSUE THREAD

**Issue by vexkiddy** [aknorw/discojs#16]
Hiya,

Does this also allow access to artist profile images and release / master artwork ?

**Comment by aknorw** [comment]
Hi @vexkiddy,

Sorry for the delay, did not see that issue 🙈 

I began working on v2 last week which is a complete rewrite of the lib. The main reasons behind this rework are:
* Support new endpoints added since the last release
* Expose types of methods + API responses

For what I've done so far, the `images` array is present in the artist-related and master/release-related endpoints.

I'll let you know when v2 is released. In the meantime, I'll make sure these images are in the responses.

**Comment by vexkiddy** [comment]
@aknorw ah ok brilliant! So the new version will have the images links for the profile and the discography ? how will this work exactly with the rate limiting on discogs side ?

**Comment by aknorw** [comment]
Actually you should be able to have the links in the response as of now. For example, using the `getArtist` method, you should end up with an `images` array.

According to the [docs](https://www.discogs.com/developers/#page:images), images are subject to rate limiting, so we might need to implement a dedicated method in the lib to include these requests in the limiter.

**Comment by vexkiddy** [comment]
and the discography images? is that possible to?

**Comment by aknorw** [comment]
We're now exposing a `fetchImage` method that allows retrieving images from the API.

**Comment by vexkiddy** [comment]
ah ok.. but this is also restricted by discogs rate limit right ?

**Comment by aknorw** [comment]
> ah ok.. but this is also restricted by discogs rate limit right ?

As explained in the docs, yes. But at least in the new version these calls are now counted in the rate limiter.

**Comment by vexkiddy** [comment]
ah ok! :D
