### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by MileanCo** [aknorw/discojs#17]
Does this repo have a way of authenticating via oauth with discogs?
https://www.discogs.com/developers/#page:authentication,header:authentication-oauth-flow

**Comment by jmnunezizu** [comment]
I'm also interested in this feature. I'm currently using a combination of this library (preferred for promises, better API) and disconnect.

**Comment by MileanCo** [comment]
I ended up just using the original Disconnect library for this on my NodeJS server.... Would be nice if this lib could do the same though

**Comment by MileanCo** [comment]
Nevermind, this approach does not work currently because you have to attach both the token and the token_secret that you get after authentication. So this lib's "userToken" option is almost useless right now.

```
5. SEND AUTHENTICATED REQUESTS TO DISCOGS ENDPOINTS
You are now ready to send authenticated requests with Discogs through OAuth. Be sure to attach the user’s OAuth access token and OAuth access token secret to each request.

To test that you are ready to send authenticated requests, send a GET request to the identity URL. A successful request will yield a response that contains information about the authenticated user.
```

**Comment by jmnunezizu** [comment]
@MileanCo could you elaborate, please?
The `userToken` option of this library works fine for me. For example, I can access a user's collection marked as "private" – something that I couldn't otherwise do.

I agree that the OAuth option is the preferred way. It also simplifies the journey from a user's point of view, given that they only need to authorise the app; rather than having to log into Discogs, go to settings, generate token, etc.

@aknorw – is there OAuth support in the pipeline, and if it isn't, could you give us some guidance on where to start, please? 

Thanks.-

**Comment by aknorw** [comment]
@jmnunezizu Thanks for pinging me, did not see this issue 🙈 

I began working on moving the entire lib to Typescript last week, so this is the first thing that will be done from me. There's a lot to be done as I want to be sure about the types of responses from the Discogs API, and their documentation is quite bad at explaining what is required or not.

I was thinking about OAuth, but I'd prefer to separate concerns: this lib is about making requests to the Discogs API, not to authenticate against it. Nevertheless, if there's an issue in the lib that prevents using this authentication flow, it needs to be fixed.

If someone wants to give it a try, I'll suggest waiting a week or so for the v2 release (written in Typescript + supporting all new endpoints added since the last release).

**Comment by jmnunezizu** [comment]
@aknorw thanks for responding back to me so quickly.

I completely agree that the app should _not_ be doing authentication. However, I think it should have the ability to include OAuth HTTP headers in the requests if those are provided.

For OAuth authentication, I'm currently using https://github.com/jmnunezizu/passport-discogs which I wrote several years ago. It's very easy to integrate and works fine with `disconnect`.

I'm happy to wait until v2 is released. Do you remember what new endpoints have been added that are currently missing in v1?

**Comment by aknorw** [comment]
@jmnunezizu I'll have a look at `passport-discogs`, thanks for that!

For new endpoints, as far as I remember:
* marketplace statistics
* list items by release/folder
* instance rating / move to another folder 
* edit custom fields

I'll make a proper PR with everything that changed asap!

**Comment by jmnunezizu** [comment]
Nice one, @aknorw! Let me know if you need any help with it.

**Comment by MileanCo** [comment]
Thanks for the updates! I agree that adding in your own oauth HTTP headers is a requirement, because you can use other libs to get the token and token_secret such as Disconnect or @jmnunezizu 's Passport lib. 

I think you can easily add the HTTP headers here with an additional if-statement and passing in token & token_secret from the configuration: https://github.com/aknorw/discojs/blob/master/src/index.js#L123

**Comment by MileanCo** [comment]
Regarding your @aknorw Typescript library, will that be a separate library? I dont think I will have much use for it personally, because my main project is using ES7 Javascript and I dont have any desire to re-write it in Typescript right now. Future projects will probably still be in ES7 JS too.... I havent used typescript yet much personally.

**Comment by aknorw** [comment]
@MileanCo Thanks for your suggestions for HTTP headers, I'll let you know if I need help!

For the typescript rewrite, the lib will still be transpiled to Javascript (even though I'll drop the UMD bundle). So even if you're not using Typescript, you'll see hints if you use Visual Studio as your IDE.

It will also help with documentation (I'll generate docs from TS comments and types) and maintainability (I'll use `io-ts` to type check responses from the Discogs API at runtime).

For the last point, it means that tests will break if Discogs devs change something without editing their documentation, but I think it's better as it would allow us to always know what we're expecting from the API - even though we did not change anything in the lib.

**Comment by aknorw** [comment]
FYI, I created a project to track the tasks that need to be done before v2 release: https://github.com/aknorw/discojs/projects/1

**Comment by aknorw** [comment]
Sorry about the (long) delay here, but this issue will be fixed in v2.

Here's an example with `passport-oauth1`:

```ts
passport.use(
  new OAuth1Strategy(
    {
      requestTokenURL: 'https://api.discogs.com/oauth/request_token',
      accessTokenURL: 'https://api.discogs.com/oauth/access_token',
      userAuthorizationURL: 'https://www.discogs.com/oauth/authorize',
      consumerKey,
      consumerSecret,
      callbackURL: 'http://127.0.0.1:8001/auth/callback',
    },
    async (
      key: string,
      secret: string,
      profile: any,
      cb: any
    ) => {
      const discojs = new Discojs({
        consumerKey,
        consumerSecret,
        oAuthToken: key,
        oAuthTokenSecret: secret,
      })

      const { id, username } = await discojs.getIdentity()
      
      ....
    },
  ),
)
```
